### ISSUE TITLE
BUG: CS_UCDs.ipynb is broken as of Aug 2023

### ISSUE THREAD

**Issue by bsipocz** [NASA-NAVO/navo-workshop#132]
The notebook consistently failing in CI since early August

**Comment by zoghbi-a** [comment]
This is failing because the name of one column changed in the MAST Tap (https://mast.stsci.edu/vo-tap/api/v0.1/hsc/):
`dbo.DetailedCatalog` changed to `dbo.detailedCatalog`. 

Because all other tables start with a capital letter, this seems to be a typos on the MAST side. @tomdonaldson?
If this was intentional, we can update the notebook.

**Comment by bsipocz** [comment]
I believe this has been resolved, at least I haven't seen this particular error in a while now.
