### ISSUE TITLE
BUG: allwise image registry searches has no results

### ISSUE THREAD

**Issue by bsipocz** [NASA-NAVO/navo-workshop#177]
This used to work as of last week:

```
import pyvo as vo
allwise_image_services = vo.regsearch(servicetype='sia', keywords=['allwise'])
```

(in the latest rendered version e.g. this is the result for this cell 

``ivo://irsa.ipac/wise/images/allwise/l3a	AllWISE L3a	AllWISE Atlas (L3a) Coadd Images``)

[Edit]: this points beyond allwise, I'm having trouble to get registry results for more than just a handful of IRSA services, both SIA and SIA2; so this is not really a notebook issue here but an upstream registry problem

**Comment by bsipocz** [comment]
I narrow this down to be likely a GAVO registry issue, the query has the expected result with the STScI registry, and also has the IRSA results using the EURO-VO registry, though it errors out when using `keywords`, but I suspect that is more related to the bug they already reported in astropy. 

cc @msdemlei

**Comment by msdemlei** [comment]
On Wed, Oct 09, 2024 at 12:09:42AM -0700, Brigitta Sipőcz wrote:
> I narrow this down to be likely a GAVO registry issue, the query
> has the expected result with the STScI registry, and also has the
> IRSA results using the EURO-VO registry, though it errors out when
> using `keywords`, but I suspect that is more related to the bug
> they already reported in astropy.

On EuroVO: No, that's yet another interop problem, this time related
to their TAP library.  We're working on figuring it out.

On the breakage: IRSA has a bug in its OAI-PMH code that kept ~1/3
of their resources out of the Heidelberg RegTAP service when it did
its periodic full re-harvest last week.  It's half repaired by now,
but some records are still affected.

Anyway: it's not your bug, and we are working on getting the
root cause fixed.

**Comment by bsipocz** [comment]
Thank you @Markus. I linked your response to our backend team at IRSA, so I think all the dots are connected now. 

I keep this issue open here until the notebooks are passing tests again, but also add the upstream label to show that fixing it is beyond this repo's TODO list.

**Comment by bsipocz** [comment]
Tests all pass now, big thanks for everyone getting to the bottom of the issues and fixing them so quickly!
